### ISSUE TITLE
Are you able to edit files in the browser ?

### ISSUE THREAD

**Issue by Nottt** [hurlenko/filebrowser-docker#1]
It doesn't work for me and I don't know why...

my config.json 

```
{
  "port": 1216,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv",
  "perm.admin": "true",
  "perm.download": "true",
  "perm.execute": "false",
  "perm.modify": "true",
  "perm.share": "true"
}
```

Have correct permissions, but when I open a file it doesn't load the editor for me

**Comment by hurlenko** [comment]
If you mean editing text files then yes, it does not seem to work in the latest (`v2.1.0`) version. Try using the previous version e.g. `hurlenko/filebrowser:v2.0.16`. Works for me.

**Comment by Nottt** [comment]
thanks bro. I was going mad with this
