### ISSUE TITLE
installed, works, but only on local network

### ISSUE THREAD

**Issue by Shahin-rmz** [hurlenko/filebrowser-docker#17]
Hello
Thanks for making and maintaining such great drop box alternative.
I am self hosting the file browser on my Raspberry pi.
on local network can reach it without any problems.
How ever when trying to reach it via Internet, it just don't load.
![image](https://user-images.githubusercontent.com/32805117/152800031-c1b77d34-68e4-466c-844d-a24165d62c50.png)
What is the problem?

**Comment by hurlenko** [comment]
Hello,
How do you run it? If it works locally, most likely there's a problem with your setup

**Comment by Shahin-rmz** [comment]
> Hello, How do you run it? If it works locally, most likely there's a problem with your setup

Hello,
Yes that was a problem with my proxy configuration setup.
Works perfectly.
Thanks
