### ISSUE TITLE
Being about to add Custom Branding.

### ISSUE THREAD

**Issue by JMast3rs** [hurlenko/filebrowser-docker#2]
Is it possible to be about to add Custom Branding when using a docker-compose file.

**Comment by hurlenko** [comment]
You can mount custom directory with your branding assets according to the [docs](https://filebrowser.org/configuration/custom-branding) and use docker-compose [`command`](https://docs.docker.com/compose/compose-file/#command) to set branding directory and start filebrowser.
Another option is to upload the assets manually using the webui and configure branding via `Settings → Global Settings`.
