### ISSUE TITLE
Control the name of the container in Portainer

### ISSUE THREAD

**Issue by ThaMattie** [hurlenko/filebrowser-docker#22]
I'm using Portainer with a compose file, and everything I add gets the container name that is the same name as the stack, but when I pull this one I get container name filebrowser-filebrowser-1 (instead of just filebrowser).
This messes up some automated processes that monitor the proxy and docker.
Is this something that you control?

**Comment by hurlenko** [comment]
No, it is just a default. You can set the container name to whatever you want

**Comment by ThaMattie** [comment]
I can change it afterwards, but every time I pull the image again, it changes it back, and I have no clue how to control this (as none of the other images I pull do this)

**Comment by hurlenko** [comment]
I don't have portainer to try it out, but you usually set the container name the moment you create it. If you're using docker compose, have you tried using [container_name](https://docs.docker.com/compose/compose-file/#container_name)?

**Comment by ThaMattie** [comment]
Doh, I missed that one, I do have that set in all my other compose files, but somehow forgot it here, thanks, that did it.
