### ISSUE TITLE
Customizable Disclaimer and Footer

### ISSUE THREAD

**Issue by swatoner** [hurlenko/filebrowser-docker#23]
Is it possible to add a customizable Disclaimer and Footer in the login page?

Want to clarify upon login that only specific file types are allowed to be uploaded.

**Comment by DevArctic** [comment]
@swatoner I think the way to do that would be to edit the source of 'filebrowser' yourself and point the script that creates the container to your modified source. It's not exactly a container issue.

**Comment by swatoner** [comment]
Sorry, I noticed long after that i reported an issue in incorrect github.... :(
