### ISSUE TITLE
change port 443 8080 is possible?

### ISSUE THREAD

**Issue by Stephen988** [hurlenko/filebrowser-docker#3]
Hi Hurlenko, I have already ports 443 and 8080 used by other container is possbile use others?

**Comment by hurlenko** [comment]
Hi @Stephen988 !

Sorry for the late response. `8080` is the port inside the container, it won't conflict with other containers/host ports. When running the container you can map it to whatever host port you want.

**Comment by Stephen988** [comment]
> Hi @Stephen988 !
> 
> Sorry for the late response. `8080` is the port inside the container, it won't conflict with other containers/host ports. When running the container you can map it to whatever host port you want.

Hi @hurlenko not worry you are very kind, if have deployed stack with 8081:8080 but when open new tab, ip_server:8081 I have blank page.
p.s. I'm on raspberry pi 4

**Comment by hurlenko** [comment]
I just tried executing `docker run -d --name filebrowser -p 8081:8080 hurlenko/filebrowser` and everything works as expected: filebrowser is accessible on `localhost:8081`. Check your proxy settings If you are running your services behind proxy. You can check basic Nginx config in the Readme. You may also need to update your firewall rules to allow incoming external connections (connections to your external IP, not localhost) to this port

**Comment by Stephen988** [comment]
> I just tried executing `docker run -d --name filebrowser -p 8081:8080 hurlenko/filebrowser` and everything works as expected: filebrowser is accessible on `localhost:8081` as well as on `<external_ip>:8081`. Check your proxy settings If you are running your services behind proxy. You can check basic Nginx config in the Readme. You may also need to update your firewall rules to allow incoming external connections (connections to your external IP, not localhost) to this port

again nothing.. my stack is this:
`version: 2

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: 1001:100
    ports:
      - 8081:8080
    volumes:
      - /srv:/data
      - /srv/dev-disk-KINGSTON/appdata/filebrowser:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always`

I don't use proxy or other, I need to put 8080 and 8081 in router ports tcp/udp?

**Comment by hurlenko** [comment]
Tried this config:
```yaml
version: "2"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: 1001:100
    ports:
      - 8081:8080
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
```

Everything works correctly. I don't know what is the reason for your issue but it has nothing to do with the docker image itself. You can search for solution on Raspberry Pi forums or Stackoverflow.
