### ISSUE TITLE
Please update docker image for filebrowser v2.24.0

### ISSUE THREAD

**Issue by libook** [hurlenko/filebrowser-docker#33]
https://github.com/filebrowser/filebrowser/releases/tag/v2.24.0

**Comment by mwaldrich** [comment]
@hurlenko What needs to be done to get this out? Is there any way we can help? I think a lot of people would benefit from this. The release that the current version is based off of (2.23.0) has a lot of bugs.

**Comment by mwaldrich** [comment]
FYI filebrowser just released [2.26.0](https://github.com/filebrowser/filebrowser/releases/tag/v2.26.0)

**Comment by mwaldrich** [comment]
Now builds v2.26.0 in #35

**Comment by hurlenko** [comment]
It took me a while, but it should be fixed now
