### ISSUE TITLE
Multiple DATA_DIR are possible?

### ISSUE THREAD

**Issue by steakhutzeee** [hurlenko/filebrowser-docker#4]
Hi, is it possible to use more then one DATA_DIR? If yes, how can i do it?

Thanks!

**Comment by hurlenko** [comment]
Hi @steakhutzeee, sorry for the late response.

If I understand you correctly, you want to attach multiple host directories to the container. `\data` is used as the root directory for filebrowser inside the container. You can attach multiple host directories as `\data` subdirectories: `-v /my_host_dir1:/data/dir1 -v /my_host_dir2:/data/dir2` etc

**Comment by steakhutzeee** [comment]
> 
> 
> Hi @steakhutzeee, sorry for the late response.
> 
> If I understand you correctly, you want to attach multiple host directories to the container. `\data` is used as the root directory for filebrowser inside the container. You can attach multiple host directories as `\data` subdirectories: `-v /my_host_dir1:/data/dir1 -v /my_host_dir2:/data/dir2` etc

Hi! That was exactly my question. Thanks!
Just a thought, nothing important. Could be possible to remove "data" as the name of the tab and instead use "File Browser" or something else? But again this is just something cosmetic. Thanks again :)

**Comment by hurlenko** [comment]
filebrowser sets the name of the tab to the name of the currently opened file or directory. You can go to the official filebrowser documentation and check if there's a way to change this behavior. You can change the [default root dir](https://github.com/hurlenko/filebrowser-docker/blob/d89d42768de85c002a6bdc6073fb209744189243/Dockerfile#L37) `\data` to whatever you want: `docker run --name filebrowser -v /mydir:/FileBrowser -p 8080:8080 hurlenko/filebrowser --root=/FileBrowser --address=0.0.0.0 --database=/config/filebrowser.db`

You will only see `FileBrowser` if you're inside the root directory, if you move to any other directory you will see that the name of the tab is changed to that directory's name

**Comment by steakhutzeee** [comment]
> 
> 
> filebrowser sets the name of the tab to the name of the currently opened file or directory. You can go to the official filebrowser documentation and check if there's a way to change this behavior. You can change the [default root dir](https://github.com/hurlenko/filebrowser-docker/blob/d89d42768de85c002a6bdc6073fb209744189243/Dockerfile#L37) `\data` to whatever you want: `docker run --name filebrowser -v /mydir:/FileBrowser -p 8080:8080 hurlenko/filebrowser --root=/FileBrowser --address=0.0.0.0 --database=/config/filebrowser.db`
> 
> You will only see `FileBrowser` if you're inside the root directory, if you move to any other directory you will see that the name of the tab is changed to that directory's name

I see, thank you very much! 
Speakinig, i can't see the size of the directories, only a "-", but i can see the size of single files. Any idea why?

**Comment by hurlenko** [comment]
I thinks this is by design but you better ask in [filebrowser/filbrowser](https://github.com/filebrowser/filebrowser) github repo

**Comment by steakhutzeee** [comment]
Will try, thanks. Closing the ticket.
