### ISSUE TITLE
tls/https support

### ISSUE THREAD

**Issue by sungle3737** [hurlenko/filebrowser-docker#5]
I could set filebrowser tls/https option locally
docker with https support will be great feature

**Comment by hurlenko** [comment]
Hi @sungle3737 !

Sorry for the late response. You can run this docker container behind some web server like Nginx, which is what I would recommend. You can check the example configuration in the readme file. Another option is to use filebrowser directly as it supports tls natively. All you need to do is mount you privatekey and certificate into the container and point filebrowser to those files via environment variables like so:

```
docker run --name filebrowser -p 443:8080 -v `pwd`/data:/data -v `pwd`/config:/config -e FB_CERT=/config/tls/domain.cert.pem -e FB_KEY=/config/tls/private.key.pem -e FB_ADDRESS=my.site hurlenko/filebrowser
```

**Comment by sungle3737** [comment]
Thanks for good answer

**Comment by benwiley4000** [comment]
Thank you @hurlenko this helped (in my case I had to remove the FB_ADDRESS variable). I'm serving on a custom port that is not 80 or 443.

I had one question though, what's the best way to automatically forward http requests to https? If I don't explicitly type https:// then I end up with an error about an HTTP request being sent to an HTTPS server.
